name: 'Setup Build Environment'
description: 'Sets up Node.js, pnpm, Rust, and Tauri dependencies for building'
inputs:
  node-version:
    description: 'Node.js version to setup'
    required: false
    default: '22'
  rust-toolchain:
    description: 'Rust toolchain to install'
    required: false
    default: 'nightly'
  tauri-deps:
    description: 'Install Tauri dependencies'
    required: false
    default: 'false'
  cache-key-suffix:
    description: 'Additional suffix for cache keys'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Setup Rust
      if: inputs.rust-toolchain != 'none'
      shell: bash
      run: |
        rustup toolchain install ${{ inputs.rust-toolchain }} --profile minimal --no-self-update
        rustup default ${{ inputs.rust-toolchain }}
        rustc --version
        cargo --version

    - name: Setup Rust cache
      if: inputs.rust-toolchain != 'none'
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          backend/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ inputs.cache-key-suffix }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install Tauri dependencies (Linux)
      if: inputs.tauri-deps == 'true' && runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          libwebkit2gtk-4.1-dev \
          librsvg2-dev \
          libxdo-dev \
          webkit2gtk-driver \
          xvfb
